# CE888: Data Science and Decision Making Lab 1


Over today's practice you'll learn:
* to use JuPyter notebooks to quickly prototype code and show results
* the numerical Python library

This lab is divided in two parts. In each of them, you will have to fill in the gaps following the instructions given.
The prompts for you to write code will look like this:

In [ ]:
#<------------INSERT CODE HERE------------>

This might involve more than one line of code from you!

Do **not** delete code from the notebook.

Let's start!

## Part 1

In the first part of the lab we're going to check your Python skills and, in particular, we will ask you to create some functions to operate on vectors and matrices.



### Operations with vectors

In [1]:
# Let's create a vector. We can do this as a Python built-in type: the list
vector1 = [1, 2, 4, 78, 93] # we declare the vector as a list of elements

print(vector1)
print("The vector has %d elements" % len(vector1))

[1, 2, 4, 78, 93]
The vector has 5 elements


In [60]:
# Let's add a number to every element of the vector.
## Exercise: create a function that, given a vector and a number,
## returns the addition of that number to each element of the vector

# import numpy as np

def vector_plus_num(vector, number):
    
    #<------------INSERT CODE HERE------------>
        
    vector = [x+number for x in vector]
     
    return vector

In [61]:
# Let's test your function:
print(vector_plus_num(vector1, 5))
print(vector_plus_num(vector1, -33))

[6, 7, 9, 83, 98]
[-32, -31, -29, 45, 60]


What if we now wanted to mutiply a number and a vector? **Do not do it**, just think about what you'd need!

And what if we want to calculate the mean value of your vector?

In [17]:
## Exercise: create a function that, given a vector,
## returns the mean value of its elements.
def vector_mean(vector):
    
    #<------------INSERT CODE HERE------------>
          
    return sum(vector) / len(vector) 

vector = [4, 5, 7, 81, 96]
mean = vector_mean(vector)

In [19]:
# Now test your function:

#<------------INSERT CODE HERE------------>

print("Mean of the vector =", round(mean, 2))

Mean of the vector = 38.6


We will now work on operations between pairs of vectors.

In [20]:
# Now let's create a new vector, called vector2, of the same length as vector1.
# We will then look at operations with multiple vectors, 
# such as adding and subtracting them, and vector multiplications.
vector2 = [5, 8, 11, 18, 88] #<------------INSERT CODE HERE------------>

assert len(vector1) == len(vector2), "The vectors are not of the same length"

In [21]:
# Create a function that returns new vector of the same length as vector1 and vector2, 
# for which each element is the sum of the corresponding elements from vector1 and vector2.

# Feel free to create a function to do this!

def add_two_vectors(vector1, vector2):
    #<------------INSERT CODE HERE------------>
    
    sumVec = [x+y for x,y in zip(vector1, vector2)]
    
    
    return sumVec

In [22]:
# Let's test your function:
print(add_two_vectors(vector1, vector2))
print(add_two_vectors(vector1, [1, 2, 3]))
# If the second print resulted in an error, don't worry about it for now!

[6, 10, 15, 96, 181]
[2, 4, 7]


How about the multiplication of vectors?
There are two types of vector multiplications:
* The dot product (or scalar product) takes two vectors and returns a scalar.
* The cross product (or vector product) takes two vectors and returns another vector.

Now let's create a function that returns the scalar product of two vectors.

This can be done by multiplying pairs of elements and adding the result:

A = [A1, A2, A3, ..., An]

B = [B1, B2, B3, ..., Bn]

A · B = A1·B1 + A2·B2 + ... An·Bn

In [50]:
def scalar_product(vec1, vec2):
    #<------------INSERT CODE HERE------------>
    
    scalarProduct = sum(x*y for x,y in zip(vec1,vec2))
    
    # scalarProduct = np.dot(vector1,vector2)
    
    return scalarProduct

In [53]:
# Test your function

#<------------INSERT CODE HERE------------>

print(scalar_product(vector1, vector2))

15021


### Operations with matrices

Again, there are multiple things we can do with matrices. For example, adding/subtracting/multiplying a number to each element of a matrix and matrix multiplication.

We're going to attempt the last one only.

In [29]:
# Create a function that receives two matrices as input and returns the matrix multiplication of the two
# If you don't know how to multiply two matrices, check:
# https://en.wikipedia.org/wiki/Matrix_multiplication#Definition

def matrix_multiplication(matrix1, matrix2):
    
    #<------------INSERT CODE HERE------------>
    
    zip_matrix2 = zip(*matrix2)
    multipl_result = [[sum(ele_matrix1*ele_matrix2 for ele_matrix1, ele_matrix2 in zip(row_matrix1, col_matrix2)) 
             for col_matrix2 in zip_matrix2] for row_matrix1 in matrix1]

    return multipl_result

In [30]:
# And let's test your function:
# NOTE: some of the tests below will give errors. Don't worry about them!
matrixA = [[1, 2, 3], [1, 2, 3]]
matrixB = [[5, 6, 7], [5, 6, 7], [5, 6, 7]]
matrixC = [[8, 9], [8, 9], [8, 9], [8, 9]]
matrixD = [[10, 11], [10, 11], [10, 11]]

In [31]:
print(matrix_multiplication(matrixA, matrixB))

[[30, 36, 42], []]


In [32]:
print(matrix_multiplication(matrixA, matrixC))

[[48, 54], []]


In [33]:
print(matrix_multiplication(matrixD, matrixA))

[[21, 42, 63], [], []]


Hopefully this has convinced you that operating with vectors and matrices like this is not the best way.
Now we will turn to the second part of this lab, in which you will be introduced to the numerical Python library, *numpy*.

## Part 2: Numpy


Numpy has a built-in type called the *ndarray*. 

In [62]:
import numpy as np # Importing convention for Numpy

#### Creating and manipulating arrays

In [63]:
# Create arrays with a specified data type

arr = np.array([1, 2, 3], dtype=np.float32)
print(arr)
print(arr.dtype)

arr = np.array([1+2j, 3-4j], dtype=np.complex64)  # an array of complex numbers
print(arr)
print(arr.dtype)

arr = np.array([0, 1, 1], dtype=np.bool)  # an array of True/False values
print(arr)
print(arr.dtype)

# We can also create arrays from the vectors and matrices we had before.
arr = np.array(matrixA)
print(arr)
print(arr.dtype)
print(arr.shape)

arr = np.array(vector2)
print(arr)
print(arr.dtype)
print(arr.shape)


[1. 2. 3.]
float32
[1.+2.j 3.-4.j]
complex64
[False  True  True]
bool
[[1 2 3]
 [1 2 3]]
int64
(2, 3)
[ 2  3  4 79 95]
int64
(5,)


In [64]:
arr_range2 = np.arange(10)
print(arr_range2)

# Retrieving information on the array
print("shape:", arr_range2.shape)
print("dtype:", arr_range2.dtype)
print("dim:", arr_range2.ndim)
print("itemsize:", arr_range2.itemsize)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
dtype: int64
dim: 1
itemsize: 8


In [65]:
# We can use the np.arange function to create a range of values:
arr = np.arange(0, 100, 5) #np.arange(start, stop, pace)
print(arr)
# Note: is the last value (100) included?

# Similarly, we can use np.linspace:
# np.linspace(start, stop, num_of_elements, endpoint=True) 
arr = np.linspace(0, 10, 20)
print(arr)
# Note: is the last value (10) included now?

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [66]:
arr_2d = np.array([(1.5, 2, 3), (4, 5, 6)]) # creating an array from a list of tuples
print(arr_2d)
print(arr_2d.shape)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
(2, 3)


In [67]:
# Slicing (i.e., accessing specific elements of the array)

print("arr_2d[0,0] :", arr_2d[0, 0])
print("arr_2d[0,:] : ", arr_2d[0, :])
print("arr_2d[:,0] :", arr_2d[:, 0])

print(arr_2d[arr_2d > 2])

arr_2d[0,0] : 1.5
arr_2d[0,:] :  [1.5 2.  3. ]
arr_2d[:,0] : [1.5 4. ]
[3. 4. 5. 6.]


In [73]:
# Other types of arrays

zeros = np.zeros((10, 10))
print(zeros)
# print the shape of zeros
#<------------INSERT CODE HERE------------>
print(zeros.shape)

ones = np.ones((4, 4))
print(ones)

# print the shape of ones
#<------------INSERT CODE HERE------------>
print(ones.shape)

print(ones.reshape(2, 8))
# print the shape of ones
#<------------INSERT CODE HERE------------>
ones_reshape = ones.reshape(2, 8)
print(ones_reshape.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(10, 10)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
(2, 8)


In [76]:
# We can also use numpy to generate random values.
randn = np.random.randn(1, 1000)
# print the shape of randn
#<------------INSERT CODE HERE------------>
print(randn.shape)

# print the first 10 elements of randn. What happens if you re-run this code?
#<------------INSERT CODE HERE------------>

print(randn[:10])

(1, 1000)
[[-1.07664635e+00  4.23331645e-01 -1.46419626e+00 -1.00945011e-01
   1.09810666e+00 -1.34829635e+00  9.40802672e-01 -1.05557863e+00
  -1.19638256e+00 -1.28731966e+00 -1.22174045e+00 -1.23830264e+00
  -1.82623225e+00 -1.12425749e+00  1.02678982e+00  3.78736747e-01
  -2.10398535e+00  1.50220938e-01  7.13571026e-03  3.99299686e-01
  -5.54801004e-01 -9.10322964e-01  1.28794087e-01  2.21295065e+00
  -1.53290717e+00 -1.35694166e+00  2.36935540e-01 -5.48093058e-01
   5.67710505e-01 -2.14143688e+00 -5.35016933e-01  6.90573391e-01
  -2.34310582e+00 -3.01937723e-02  7.50450983e-01 -2.28311582e+00
  -2.93980874e-01  8.70358176e-01  2.44608895e+00  1.58398160e+00
  -3.12755569e-01  8.59966914e-02 -4.84856275e-02 -1.83820835e+00
  -1.47987867e-02 -9.54303317e-01 -5.37611439e-01 -1.98705832e+00
  -1.00722560e+00 -2.02986484e+00  1.06834993e+00 -5.79613268e-01
  -5.50474678e-01  2.14221569e+00  6.12721089e-01 -6.22339115e-01
  -2.10719739e-01  1.30254045e+00 -7.33965109e-01 -7.45737771e-01


In [78]:
np.random.seed(23)

# Generate a new array of random numbers, this time of shape (3, 2) and print it.
# What happens when you re-run the code now?
# TIP: you might want to save the result to compare the previous and the new one

#<------------INSERT CODE HERE------------>
rand1 = np.random.rand(3,2)
print(rand1)
# Think: what does np.seed() do? (Use Google if you don't know!)

[[0.51729788 0.9469626 ]
 [0.76545976 0.28239584]
 [0.22104536 0.68622209]]


#### Combine arrays

In [82]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7 , 8]])

# Print the shapes of arr1 and arr2 and cat after each of the types of concatenations.
# Concatenating arrays is a very common operation. Make sure you understand it!
# TIP: it might help you to print the actual cat array after each type of concatenation too

#<------------INSERT CODE HERE------------>

print(arr1.shape)
print(arr2.shape)

# axis_a = np.concatenate((arr1, arr2), axis=0)
# axis_b = np.concatenate((arr1, arr2), axis=1)
axis_c = np.concatenate((arr1, arr2), axis=None)

# print(axis_a)
# print(axis_b)
print(axis_c)

# print(axis_a.shape)
# print(axis_b.shape)
print(axis_c.shape)

# concatenate along the row
cat = np.concatenate((arr1, arr2), axis=0)
#<------------INSERT CODE HERE------------>
print(cat)
print(cat.shape)

# concatenate along the column
cat = np.concatenate((arr1, arr2), axis=1)    
#<------------INSERT CODE HERE------------>

print(cat)
print(cat.shape)

# stack arrays vertically
cat = np.vstack((arr1, arr2))
#<------------INSERT CODE HERE------------>

print(cat)
print(cat.shape)

# stack arrays horizontally
cat = np.hstack((arr1, arr2))
#<------------INSERT CODE HERE------------>
print(cat)
print(cat.shape)


(2, 4)
(2, 4)
[1 2 3 4 1 2 3 4 5 6 7 8 5 6 7 8]
(16,)
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
(4, 4)
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
(2, 8)
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
(4, 4)
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
(2, 8)


#### Operations with arrays

In [99]:
#Let's create a couple of vectors using numpy
v1 = np.array([20, 30, 40, 50])
v2 = np.arange(4)

print(v1)
print(v2)
#And a couple of matrices
mat1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
mat2 = mat1.T # this is the transpose of mat1

[20 30 40 50]
[0 1 2 3]


In [97]:
# Add a number to an array of 1-D (i.e., a vector)
print(5 + v1)
# Compare the line above to your function vector_plus_num(vector, number) from Part 1.

# Does your function work with matrices?

# How do you add a number to a np.array object? Try adding 2367 to mat1

#<------------INSERT CODE HERE------------>

print(np.insert(mat1, 4, 2367, axis=1))
# print(np.insert(mat1, 1, 2367, axis=0))
# print(np.insert(mat1, 2, 2367))

[25 35 45 55]
[[   1    2    3    4 2367]
 [   1    2    3    4 2367]]


In [100]:
# Let's try to add and subtract vectors now:
print("Adding two vectors", v1 + v2)
print("Subtracting two vectors", v1 - v2)

# What happens if you try to add two vectors of different length?


# Square root of each elemnt of v2:
print(np.sqrt(v2))

# Calculate the logarithm of each element of v1
# TIP: check if you can do this using some numpy function!

#<------------INSERT CODE HERE------------>

print(np.log(v1))
print(np.log10(v1))

Adding two vectors [20 31 42 53]
Subtracting two vectors [20 29 38 47]
[0.         1.         1.41421356 1.73205081]
[2.99573227 3.40119738 3.68887945 3.91202301]
[1.30103    1.47712125 1.60205999 1.69897   ]


### Multiplication of vectors

There are a number of functions in numpy that you can use to multiply vectors and matrices.

Scalar product of two vectors: np.dot(vector1, vector2)

Vector product of two vectors: np.cross(x, y)

In [102]:
# Calculate the scalar product of v1 and v2 using your function from part 1 and the numpy function.
#<------------INSERT CODE HERE------------>

scalarProduct = np.dot(vector1,vector2)

# Check if the result is the same using your function from Part 1

#<------------INSERT CODE HERE------------>
print(scalarProduct)


v3 = np.random.randn(4000)
v4 = np.random.randn(4000)
# Calculate the scalar product of v3 and v4 using your function from part 1 and the numpy function.
# Compare the time it takes to execute each of them.
# HINT: https://stackoverflow.com/questions/7370801/measure-time-elapsed-in-python

#<------------INSERT CODE HERE------------>

print(scalar_product(v3, v4))
print(np.dot(v3,v4))


15021
-47.665451057784686
-47.66545105778464


In [112]:
# Calculate the vector product of v1 and v2 using the numpy function.

#<------------INSERT CODE HERE------------>

v1 = [20, 30, 40]
v2 = [0, 1, 2]

print(np.cross(v1, v2))

[ 20 -40  20]


### Matrix multiplication

This can be done on numpy using: np.matmul(a, b)

In [115]:
# Check the result of multiplying mat1 and mat2 using the numpy function and the one you created in part 1.
# Check the execution time for each of them. Which one is faster? 

#<------------INSERT CODE HERE------------>

print(np.matmul(mat1, mat2))

# Is it the same result?

#<------------INSERT CODE HERE------------>
print(matrix_multiplication(mat1, mat2))

[[30 30]
 [30 30]]
[[30, 30], []]


**Plotting a function**

In [116]:
import matplotlib.pyplot as plt

In [117]:
plt.figure()
plt.plot(t, sin)
plt.xlabel("Time")
plt.ylabel("sin(1/4*pi*t)")
plt.title("Sinusoidal function")
plt.show()

NameError: name 't' is not defined

<Figure size 432x288 with 0 Axes>

In [ ]:
print(np.max(sin))
print(np.min(sin))

## Elementwise minimum and maximum
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

In [118]:
# Statistical summaries 

print(np.mean(randn))
print(np.median(randn))
print(np.std(randn))



0.04530141371765461
0.06462433906215606
1.0229911859336371


Create a 5 (channels) x 100 (samples) matrix of random integers between 0 and 543 and retrieve the following information:
    - the max, min, mean of all samples.
    - the mean and variance of each channel


In [ ]:
#<------------INSERT CODE HERE------------>

Use the function hist() from matplotlib to show the histogram of values of the third channel.

In [ ]:
#<------------INSERT CODE HERE------------>